# Generated by Django 5.0.6 on 2024-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="team-4.jpg", upload_to="profile_pics"),
        ),
    ]
