# Generated by Django 5.0.6 on 2024-06-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_address_profile_city_profile_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_balance",
            field=models.FloatField(default=0.0),
        ),
    ]
